version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/  
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn ch4.wsgi -b 0.0.0.0:8000 # new 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=4WdVM4mDzgd2pi-s4uz19j-UVU_2PYBGqpbm5mY-slBMOzXLLq8"
      - "DJANGO_DEBUG=True"
volumes:
  db_data:
